web:
  build: .
  command: 'bash -c ''bundle exec rackup config.ru -p $PORT'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'

